# Generated by Django 4.2.23 on 2025-08-20 16:54

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_format_genre_product_formats_product_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=isbn_field.fields.ISBNField(default=3, max_length=28, unique=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
